### ISSUE TITLE
Bug/Functionality: Inconsistent action when filling dates

### ISSUE THREAD

**Issue by Karyudo** [olehj/disklocation#251] opened 2024-01-18 19:45 UTC
When filling in Purchase Date, after typing a four-digit year, the Year stays highlighted, instead of moving to the two-digit Month column. After typing the two-digit month, the highlighting (correctly, in my opinion!) moves to the Day column.

**Comment by olehj** [comment] 2024-01-20 00:39
The dates are stored in ISO format, the only really sensible way of storing a date. What you enter in the browser are depending on your locale setting for your browser and has nothing to do with the plugin itself. Not sure what you mean with the highlighting etc. but it's just a part of pure HTML5.

If it's about how US dates works etc. then I can't be bothered, so I'm closing this.

**Comment by Karyudo** [comment] 2024-01-20 00:48
No, I'm 100% with you: ISO 8601 is the best and only date format! I'm in
Canada, and it drives me nuts that both US and UK date formats get used
here. Microsoft and Google both try to force MM/DD/YYYY, rather than just
letting me use something superior. But I don't think that's the issue here.

If I type a four-digit year in the Year field, the cursor/highlighting
stays on Year, and doesn't move to Month. It will also accept a six-digit
year, apparently. This seems wrong. If it's not a bug, it's a clunky UI
choice.

If I type a two-digit month in the Month field, the cursor/highlighting
correctly moves to Day. This is how Year should also work, but doesn't.

Cheers,
Greg

**Comment by Karyudo** [comment] 2024-01-20 00:52
Made a quick video to show the error.

**Comment by olehj** [comment] 2024-01-21 09:49
Looks like I found the cause, didn't know it was a thing that it expanded beyond 4-digit year.

**Comment by Karyudo** [comment] 2024-01-21 17:42
Yeah, I guess if YYYY is the last thing one types (whether DD.MM or MM.DD precedes it) then it's pretty easy to not notice that YYYYYY is also accepted! Glad to see you found a fix, and it's great to hear it will be implemented in the next release. Thanks!

**Closed** 2024-02-08 22:49 UTC
Labels: improvement, done
