### ISSUE TITLE
No overview Dashboard after installation

### ISSUE THREAD

**Issue by cryd-s** [olehj/disklocation#333] opened 2024-10-28 07:39 UTC
![image](https://github.com/user-attachments/assets/3c9e7286-af7d-4a54-bf39-ac2e018cd500)

need help to get my start dashboard back

**Comment by cryd-s** [comment] 2024-10-28 08:09
![image](https://github.com/user-attachments/assets/a1d1a8d4-7f5a-4742-8fbf-6c4c4506d60b)

**Comment by olehj** [comment] 2024-10-28 09:40
Duplicate of #328 and #334

**Closed by olehj** 2024-10-28 09:40 UTC
